services:
  app:
    build: .
    container_name: stylistiq_be
    ports:
      - '127.0.0.1:3099:3000'
    env_file:
      - .env.prod
    environment:
      NODE_ENV: prod
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      ELASTIC_SEARCH_URL: ${ELASTIC_SEARCH_URL}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    command: |
      sh -c "
        npm run start:dev
      "

  mysql:
    image: mysql:8.0
    container_name: mysql_stylistiq
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '127.0.0.1:3310:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uroot']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # elasticsearch:
  #   image: elasticsearch:8.11.2
  #   container_name: elasticsearch_stylistiq
  #   environment:
  #     - discovery.type=single-node
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ports:
  #     - "127.0.0.19200:9200" # Expose Elasticsearch HTTP port
  #   volumes:
  #     - es_data:/usr/share/elasticsearch/data # Persist Elasticsearch data
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\|yellow\"'"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10

volumes:
  mysql_data:
